### ISSUE TITLE
ScriptResource Error "Method invocation is supported only on core types in this language mode"

### ISSUE THREAD

**Issue by nmdange2** [PowerShell/PSDscResources#123]
I am attempting to execute a ScriptResource on a Hyper-V host with a Code Integrity Policy applied.  It fails with this error:
PowerShell DSC resource MSFT_ScriptResource  failed to execute Test-TargetResource functionality with error message:
Cannot invoke method. Method invocation is supported only on core types in this language mode.

I believe this is due to PowerShell Constrained Language Mode being enabled when User Mode Code Integrity is enabled.  I just want to confirm that my understanding is correct and there is no alternative way to get a Script resource to run.

**Comment by PlagueHO** [comment]
Hi @nmdange2 - thanks for raising this and sorry for taking so long to get back to you.

This is likely to be a result of PowerShell Constrained Language Mode as you say. The Script resource does use and depend on a number of things that Constrained Language Mode prevents. In fact many DSC resources might end up being blocked (not by design) due to various reasons.

**Comment by gaelcolas** [comment]
Hi @nmdange2,

You're right, DSC Script Resources are not allowed with Device Guard because of [CVE-2018-8212](https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE-2018-8212).

Here's [a great article about the exploit by the researcher enigma0x3 who found it](https://enigma0x3.net/2018/10/10/cve-2018-8212-device-guard-clm-bypass-using-msft_scriptresource/).

I **think** (TBC) that this can be worked around by creating your Custom Resource instead of using a Script Resource.

**Comment by nmdange2** [comment]
Hi didn't notice the other updates, but it seems if I add the PSDscResources module hash to the Code Integrity Policy, it is able to execute.
