### ISSUE TITLE
WindowsFeature: Can't be used on Windows client OS

### ISSUE THREAD

**Issue by andikrueger** [PowerShell/PSDscResources#131]
Today I was impacted by the following limitation of the WindowsFeature Resource:

"Installing roles and features using PowerShell Desired State Configuration is supported only on Server SKU’s. It is not supported on Client SKU."

There is a possible way to add or remove features from a windows client OS. It would be great to have this feature set added to the resource.

I used the following snippet to get around my issue. This approach could be generalized and is not limited to activate Hyper-V:

```
        Script Hyper-V
        {
            GetScript  = {
                Write-Verbose "Get current status for Microsoft-Hyper-V Feature"
                $hyperVFeatureState = Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V -Online -ErrorAction SilentlyContinue
                return @{
                    Result = $hyperVFeatureState
                }
            }

            SetScript  = {
                Write-Verbose "Activating Microsoft-Hyper-V Feature"
                Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
            }

            TestScript = {
                Write-Verbose "Test the current status for Microsoft-Hyper-V Feature"
                $hyperVFeatureState = & ([ScriptBlock]::Create($GetScript))

                Write-Verbose "Current status is: $($hyperVFeatureState.Result.State)"

                return $hyperVFeatureState.Result.State -eq 'Enabled'
            }
        }
```

see: https://gist.github.com/andikrueger/ac789a83f26c7cc1ec2b61302f69a280#file-scriptresourcehyper-v-ps1

**Comment by PlagueHO** [comment]
The primary use case for DSC is for Server OS configuration, so this is why the resource doesn't already exist.

There is probably several approaches we could take here:
1. Add a new WindowsOptionalFeature resource to PSDscResources
2. Add a new WindowsOptionalFeature resource to a different module (e.g. ComputerManagement)
3. Adapt the WindowsFeature resource to function on Windows client OS.

I'm not sure about the feasibility of Option 3.

What would the community expect in general if this resource was implemented?

**Comment by PlagueHO** [comment]
I've just realized that Option 1 is out anyway as we can't add new resources to this module. The reason I suggested it was that Windows Features and Windows Optional Features are actually different things (even though they behave in a similar way). But I agree, people do generally think of them in the same way, so they would expect them to be part of WindowsFeature.

Option 3 was suggested as if we needed to add a new resource (e.g. because it wasn't possible to get it into WindowsFeature) then we'd need to put this elsewhere. ComputerManagement is probably the next best candidate.

**Comment by kilasuit** [comment]
Option 3 with another property that takes values of Client/Server that then calls in a switch within the actual Get/Set/Test Methods would be my ideal suggestion here @PlagueHO

**Comment by PlagueHO** [comment]
I feel a bit dumb (😊), but I just realized there is already a `WindowsOptionalFeature` resource in this module (and in xPSDesiredStateConfiguration`). @andikrueger - are you able to give this a try and see if it does the trick - and if so close this issue?

**Comment by andikrueger** [comment]
That's the way I feel right now.  Finding this repository was a challenge.  If there is even the resource now, then I could have saved us a lot of time. 

I will test it and give feedback. 

Are there any plans to consolidate the two resources?

**Comment by PlagueHO** [comment]
Do you mean consolidate WindowsFeature and WindowsOptionalFeature? I don't think this is planned. If we did do this we'd want to deprecate WindowsOptionalFeature because maintaining two resources with functionality which intersects can result in invalid configs. We would have to deprecate one of these and this would result in a breaking change - which we aren't doing in the PSDscResource module (to maintain stability in the HQRM version).

**Comment by andikrueger** [comment]
I really think, we can close this issue. Consolidating the two resources will be a lot of work and PSDscResource can be installed on WMF 5.1 systems (Windows 10) without any problem. 

It would be great, if PSDesiredStateConfiguration would be updated on a regular basis with all those fantastic resources contained in this repo here.

**Comment by mhendric** [comment]
Is there a roadmap anywhere of how changes made to xPSDesiredStateConfiguration are supposed to ultimately make it into PSDscResources (or vice versa)? If not, that may be worthwhile to put together at some point.

**Comment by PlagueHO** [comment]
I don't know recall there being one. @johlju - do you remember if there was a plan documented on how critical fixes might make it back into xPSDesiredStateConfiguration when HQRM PSDscResources was rolled out? As @mhendric says it might be good to set expectations around what might be back ported and what won't be.

**Comment by johlju** [comment]
Both of them have it's own life-cycle since one is supported by the PowerShell DSC Team (this module) and the other is supported by the community. So I think there never was a plan other then have a resource in this module replacing the built-in resource (where File resource still need to be built-in for speed). There is one more resource that was planned to be moved over (Package I think, see issue #112), and that might be accepted to this module (if approved by the DSC Team).

See an extended information around the difference between the modules in the https://github.com/PowerShell/PSDscResources/issues/97#issuecomment-389758476 (maybe this should be added to the documentation).

**Comment by mhendric** [comment]
I personally think it would be great if we could come up with and execute on a roadmap to get these two modules (PSDscResources and xPSDesiredStateConfiguration) merged down into a single module. Or at a minimum, have a strategy about how to back/forward port between them. As a new co-maintainer of both of these, it seems that it would be a lot easier from a maintenance perspective to only have a single module (with perhaps a Feature branch or something for introducing new features not yet ready for Master). And as a long time consumer of both of these modules, I think it would make it a whole lot less confusing.

I know a lot of work needs to go into xPSDesiredStateConfiguration to make it a High Quality Module, and thus make the code easily portable into PSDscResources, but I think the effort would be worth it in the long run.

Not sure the best way to collaborate on creating a roadmap for this though. Wondering if we can utilize some Azure DevOps features for this. It may be worth getting a Module (family) specific community call together to discuss this too. Thoughts?

**Comment by mhendric** [comment]
Definitely worth raising at the next call. I wonder if the 'no new resources' stance is really no new resources in general, or if it's just no new resources that don't meet the High Quality Module bar. No breaking changes makes sense, but I'm not sure why we wouldn't want to do new resources if they're high quality.

**Comment by johlju** [comment]
Unless I'm mistaken: Since this module is supported by Microsoft Support (PowerShell DSC Team), this module is meant to replace the built-in resources in PSDesiredStateConfiguration, 'no new resources' mean that Microsoft Support would need to support any new resources if we added them. So unless that support level has changed, any new resources should be approved by @kwirkykat. But we can ask on the next call how we should handle this module. 🙂

**Comment by mhendric** [comment]
Alright, starting to make more sense. Let me ask you guys this though. Are there good reasons that we should maintain overlapping resources between modules? For instance, ServiceResource vs xServiceResource. ServiceResource has already been approved for and exists in PSDSCResources. If we could somehow collapse these in PSDSCResources\ServiceResource (without introducing breaking changes), potentially we wouldn't need xPSDesiredStateConfiguration\xServiceResource at all. Then we would remove ambiguity for consumers of the modules, and make them easier to maintain (e.g. no bi-directional porting).

And I still agree that we should discuss this on the call, but it doesn't hurt to at least discuss some options in the meantime. Perhaps a new Issue would be best to discuss in though...

**Comment by andikrueger** [comment]
@mhendric Totally agree with the idea of creating a new issue to discuss the options!
