### ISSUE TITLE
Windows 10 Creators Update: Importing module MSFT_GroupResource failed with error - Method invocation failed because [System.Collections.Hashtable] does not contain a method named 'Replace'

### ISSUE THREAD

**Issue by julioct** [PowerShell/PSDscResources#58]
Tried to run my DSC configuration on a Windows 10 Creators Update Azure VM and got this error:

"DSC Configuration completed with error(s). Following are the first few: **Importing module MSFT_GroupResource failed with error - Method invocation failed because [System.Collections.Hashtable] does not contain a method named 'Replace'.**

This is using the built in desired state configuration module via the Azure DSC Extension version 2.24. The specific resource that causes the problem is this:

        Group AddTestUserToLocalAdminGroup
        {
            DependsOn = "[User]AddTestUser"
            GroupName='Administrators'   
            Ensure= 'Present'             
            MembersToInclude= "SomeUsername"
        }  

Are there any issues with the DSC Resources on Windows 10 Creators Update?

**Comment by kwirkykat** [comment]
@julioct #57 is definitely an issue.
Are you using the Group resource here from PSDesiredStateConfiguration or PSDscResources?

Neither of the Group resources even have the word 'replace' in the code, so it's probably also coming from the DSC engine or PowerShell which means that sadly I probably can't just fix this issue here in the resource module.

**Comment by kwirkykat** [comment]
@julioct Oh dear. It's with the one in PSDesiredStateConfiguration.
I'm going to try out xGroup in xPSDesiredStateConfiguration to see if that has issues as well.

**Comment by kwirkykat** [comment]
@julioct xGroup from [xPSDesiredStateConfiguration](https://github.com/powershell/xpsdesiredstateconfiguration#xgroup) still seems to work, so if you need an immediate workaround you can try out switching over to using that resource for now.

It almost the same resource as the one here in PSDscResources, just named xGroup rather than Group.
I can also submit a PR and release xPSDesiredStateConfiguration again today so that it will be the exact same resource as the one here. Just give me an hour or two.

Sorry for the trouble.

**Comment by julioct** [comment]
Thanks for investigating. XGroup indeed works! Also had to switch from the Service resource to xService due to the same problem.

**Comment by kwirkykat** [comment]
@julioct I figured out where this issue was coming from on my end, but not sure yours is the same. Do you happen to have strict mode turned on when you are running/compiling your configuration? Like `Set-StrictMode -Version 'latest'`?

**Comment by julioct** [comment]
I have never run that command in my box. But also I get the same error when deploying an unmodified Windows 10 Creators Update image to Azure. So you should get this error in any brand new installation of Windows.

**Comment by kwirkykat** [comment]
@julioct The fix for this is expected to go out in a Windows update this week.

**Comment by julioct** [comment]
Great, thanks!

**Comment by kwirkykat** [comment]
Windows Update to fix this went out on 06/15/17.
If you have the update you should have PSVersion 5.1.15063.413
