### ISSUE TITLE
Resolve clashes between PSDesiredStateConfiguration & PsDscResources

### ISSUE THREAD

**Issue by turkeys-united** [PowerShell/PSDscResources#90]
Hi,

I'm working with a configuration that uses resources from both `PSDesiredStateConfiguration` (specifically the `File` resource) & also `PsDscResources` (which doesn't have its own version of the `File` resource). I can get this working by having an `Import-DscResource` statement for `PsDscResources` & `PSDesiredStateConfiguration` is implicitly imported as needed. However, this results in a warning along the lines of "_WARNING: The configuration '...' is loading one or more built-in resources without explicitly importing associated modules. Add Import-DscResource –ModuleName 'PSDesiredStateConfiguration' to your configuration to avoid this message._", & I'd like to avoid that if I can.

Questions:

1. Is there any plan to migrate the `File` resource into `PsDscResources` so I can solely use that? Per this issue over at the `xPSDesiredStateConfiguration` repo it would appear not: [Are there any plans or is anyone working on xFile?](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/260).
2. Is there a way to explicitly import _just_ the `File` resource from `PSDesiredStateConfiguration`? I can do this for other resources, e.g. `Import-DscResource -ModuleName PSDesiredStateConfiguration -Name 'WindowsFeature'`, but attempting to do this with the `File` resource results in a "Resource does not exist" message.
3. Is there a way I can suppress the _just_ "implicit load" warning message?

My strong preference would be either 1 - Be able to use PsDscResources exclusively or 2 - Explicitly import _just_ the File resource. If I need to resort to 3, I'd need a way to ignore this specific warning, but keep any other warnings...

Thanks heaps for help or suggestions,

Dave

**Comment by mbreakey3** [comment]
Hi Dave,

Unfortunately, the best solution I have for you is to add "-WarningAction SilentlyContinue" to the call to your config. However, that will suppress all warnings which I assume is what you're trying to avoid. You could potentially write your own warning/error handling function similar to what's described in [this thread](https://stackoverflow.com/questions/1142211/try-catch-does-not-seem-to-have-an-effect) but that may be more work than what you want to put in.



To answer your questions:
1. We currently don't have a timeline for migrating the File resource. We would like to do this in the future, but currently we don't have the bandwidth.
2. This looks like a bug on our side, you should just be able to import the File resource, but it seems that there's some issue there. I'll look into this and get back to you if I have any updates. Unfortunately, we most likely will not be able to get a fix for this any time soon (if it is a bug on our side) since this is a resource that is shipped in-box and for the most part we're only releasing critical or security related updates to those resources. 
3. I don't know a better way other than what I mentioned above. Warnings are a bit more tricky to deal with than errors.

**Comment by turkeys-united** [comment]
Thanks @mbreakey3, that's kind of where I'd got to as well. Being able to use (2) would have been ideal, but in the absence of that I've restored to capturing warnings from the DSC MOF build in a variable using `-WarningVariable buildWarnings -WarningAction SilentlyContinue`, then inspecting these using a set of RegExs for "known safe" warnings that I'm happy to suppress or else I write out the warning. It's clunky but works.

**Comment by mbreakey3** [comment]
Ah, that's even a bit cleaner than what I was thinking, but certainly still clunky. Yeah, sorry I don't have a better solution for you at this time.

**Comment by johlju** [comment]
@turkeys-united Closing this issue as not fixed even if you got answers on your questions that main question, a File resource in this repo. Propose that you submit a new issue with resource proposal in this repository so that the community maybe could port the resource.

**Comment by johlju** [comment]
With port I meant to crate a File resource in this repository similar to the builtin File resource. 🙂

**Comment by kevinpohlmeier** [comment]
When you run `Get-DscResource -Module PSDesiredStateConfiguration`, you can see that the ModuleName of the File resource is blank. I guess that's why question #2 is an issue.

**Comment by PlagueHO** [comment]
Hi @kevinpohlmeier - the `File` resource is a special resource. It is actually implemented as a native WMI object. It is built-in to the OS. So we can't actually implement a version in this module - unless we rewrite it from scratch. So, that is why you won't find the `File` resource in this module or `xPSDesiredStateConfiguration`.
