### ISSUE TITLE
TestScript is not returning the expected data

### ISSUE THREAD

**Issue by rsganta** [PowerShell/PSDscResources#93]
Hi,
I am using Script to run  sn.ps1 only if the mentioned key below does not exist  . In the first run, machine will not have this and expected sn.ps1 to run. Somehow it is not running. I am wondering if the  logic in TestScript block is valid ?  Appreciate your inputs.

 Script RunSnbat
        {
        
            GetScript =
            {
                # Do Nothing 

                $strongName = "hklm:\SOFTWARE\Microsoft\StrongName\Verification" 
                $IsStrongNameExists = Test-Path $strongName  
                           
            }

            SetScript = 
            {
                
                $runSnbat =  C:\SXS\sn.ps1 
             
            }

            TestScript = 
            {
        
              
                $IsExists = $GetScript
                if ($IsExists) {return $true} else {return $false}
            }          

       }

**Comment by kwirkykat** [comment]
@rsganta There are 2 problems here:
1. `$IsExists = $GetScript` This line isn't actually executing $GetScript. It just assigns the variable $IsExists to the string that is $GetScript. Because $IsExists is assigned to a non-null string, the following if statement just evaluate if $IsExists is null (false) or not (true). Since $IsExists will never be null in this case, it will always your TestScript will always return true which means that SetScript will never run. In order to actually execute the string, you can turn the string into a ScriptBlock and then execute that with `&`. So this line in TestScript should look like this:
    `$fileExists = & ([ScriptBlock]::Create($GetScript))`
2. GetScript doesn't return a value. So even if you correctly put in the solution for issue 1, then GetScript will always return null which means that TestScript will always return false and Set will always run. You want to return the value of $IsStrongNameExists from your GetScript instead of assigning it to a variable. Like this:
 `return Test-Path -Path $strongName`

**Comment by rsganta** [comment]
thank you.  I also find the other way of the solution by putting logic directly in the test-script and so it does not depend on get-script. 
One more question, I noticed below error sometimes when I run the script. Though set executes successfully but throws the below error.
VERBOSE: [997C-DM2-TAP01]: LCM:  [ Start  Set      ]  [[Script]SecurityTokenService]
VERBOSE: [997C-DM2-TAP01]:                            [[Script]SecurityTokenService] Performing the operation "Set-TargetResource" on target "Executing the SetScript with the user supplied credential".
VERBOSE: [997C-DM2-TAP01]: LCM:  [ End    Set      ]  [[Script]SecurityTokenService]  in 0.6720 seconds.
PowerShell DSC resource MSFT_ScriptResource  failed to execute Set-TargetResource functionality with error message: An item with the same key has already been added. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
